apiVersion: v1
kind: Secret
metadata:
  name: external-provider-api-key-${EXTERNAL_MODEL}
  namespace: llm-hosting
  labels:
    inference.networking.k8s.io/bbr-managed: "true"
    inference.llm-d.ai/ipp-managed: "true"
type: Opaque
stringData:
  api-key: "${EXTERNAL_MODEL_API_KEY}"
