kind: ConfigMap
apiVersion: v1
metadata:
  name: gen-ai-aa-mcp-servers
  namespace: redhat-ods-applications
data:
  MCP-Gateway: |
    {
      "url": "${MCP_URL}",
      "description": "The MCP Gateway offers controlled access to a set of different tools"
    }
